export const DEFAULT_SETTINGS = {
  enabled: true,
  primaryColor: "#000000",
  textColor: "#FFFFFF",
  buttonText: "Add to Cart",
  position: "BOTTOM_RIGHT",
  upsellEnabled: false,
  upsellProductId: null,
  quickBuyEnabled: false,
  showCartSummary: true,
  enableQuantitySelector: true,
  openCartDrawer: true,
  showFreeShippingBar: false,
  freeShippingGoal: 5000,
  countdownEnabled: false,
  countdownEndTime: null,
  countdownDuration: 0,
  countdownText: "Offer ends in",
  trustBadgesEnabled: false,
  trustBadgesList: "secure_checkout,money_back",
  trustBadgesStyle: "icon_text",
  analyticsEnabled: false,
  lowStockEnabled: false,
  lowStockThreshold: 10,
  showDiscountBadge: false,
  smartUpsellEnabled: false,
  smartUpsellStrategy: "same_collection",
  multiCurrencyEnabled: false,
} as const;
